server:
  port: 8091

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/product_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    stream:
      bindings:
        productCreated-out-0:
          destination: product-created-topic
        productUpdated-out-0:
          destination: product-updated-topic
        productStatusChanged-out-0:
          destination: product-status-changed-topic
      kafka:
        binder:
          brokers:
            - localhost:9092

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/product_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMAS:public}