server:
  port: 8090

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_db}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMAS:public}

security:
  keycloak:
    baseUrl: ${KEYCLOAK_BASE_URL:http://localhost:8088}
    realm: ${KEYCLOAK_REALM:ecommerce-realm}
    clientUser:
      id: ${KEYCLOAK_USER_CLIENT_ID:ecommerce_client}
      secret: ${KEYCLOAK_USER_CLIENT_SECRET:Aob7naCgV1VvSpgjzSlsA8AQjUhoHmH9}
    clientAdmin:
      id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:IbT3FtIqDcV8w9B3bllDZi3zqQllnzdq}
      username: ${KEYCLOAK_ADMIN_USERNAME:admin123@gmail.com}
      password: ${KEYCLOAK_ADMIN_PASSWORD:sbu&bwln8}